version: '3'

services:
  neo4j:
    build: .
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-none}
    expose:
      - 7474
      - 7473
      - 7687
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
      - ./code:/code