version: '3'

services:
  neo4j:
    build: .
    container_name: nvdgraph
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-none}
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_heap_initial__size: 2G
    expose:
      - 7474
      - 7473
      - 7687
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./code:/var/lib/neo4j/code
      - ./conf:/var/lib/neo4j/conf
      - ./data:/data
      - ./logs:/logs