version: '3'

services:
  neo4j:
    environment:
      NEO4J_AUTH: none
    expose:
      - 7474
      - 7473
      - 7687
    image: neo4j:3.4.7
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs